/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-116344-g5c8523cef1-20240721"
#endif /* AVUTIL_FFVERSION_H */
